- name: copy war to target server
  copy:
    #src=/home/deploy/tmp/{{ app_name }}/{{ phase }}/{{ app_name }}.war dest=/tmp/ROOT.war owner=nobody group=nobody mode=0644
    src=/Workspace/chequer/chequer-admin/target/chequer-admin.war dest=/tmp/ROOT.war owner=nobody group=nobody mode=0644
  sudo: True
  ignore_errors: yes

- name: decision deploy number
  shell: cd /var/tomcat/{{ app_name }}/webapps; value=`ls *.war | cut -f1 -d'/' | sort -r | cut -c 7-15 | sed -n '1p'`; printf "%d" $((${value%%.*} + 1))
  register: deploy_version
  sudo: yes

- name: decision delete target number
  shell: cd /var/tomcat/{{ app_name }}/webapps; value=`ls *.war | cut -f1 -d'/' | sort -r | cut -c 7-15 | sed -n '1p'`; printf "%d" $((${value%%.*} - 1))
  register: delete_version
  sudo: yes

- name: copy war to catalina home
  shell: cp /tmp/ROOT.war /var/tomcat/{{ app_name }}/webapps/ROOT##{{item}}.war
  with_items: deploy_version.stdout_lines
  sudo: yes

- name: delete previous ROOT directory
  shell: >
    rm -rf /var/tomcat/{{ app_name }}/webapps/ROOT##{{item}}.war &&
    rm -rf /var/tomcat/{{ app_name }}/webapps/ROOT##{{item}}
  with_items: delete_version.stdout_lines
  ignore_errors: yes
  sudo: True


## Second Instance Deployment

- name: check second instance exist
  stat: path=/var/tomcat/{{ app_name_1 }}
  register: second_instance

- name: copy war to catalina home
  shell: cp /tmp/ROOT.war /var/tomcat/{{ app_name_1 }}/webapps/ROOT##{{item}}.war
  with_items: deploy_version.stdout_lines
  sudo: True

- name: delete previous ROOT directory
  shell: >
    rm -rf /var/tomcat/{{ app_name_1 }}/webapps/ROOT##{{item}}.war &&
    rm -rf /var/tomcat/{{ app_name_1 }}/webapps/ROOT##{{item}}
  with_items: delete_version.stdout_lines
  ignore_errors: yes
  sudo: True
  when: second_instance.stat.exists == True
