- name: create directory
  file: path=/var/nginx/{{ item.path }} owner=nobody group=nobody state=directory recurse=yes
  with_items:
    - {path: "conf"}
    - {path: "logs"}
    - {path: "data"}
    - {path: "cache"}
  sudo: yes

- name: rename path for symbolic link
  command:
    mv /usr/local/nginx/{{ item.path }} /usr/local/nginx/_{{ item.path }} removes=/usr/local/nginx/{{ item.path }}
  with_items:
    - {path: "conf"}
    - {path: "logs"}
  sudo: yes

- name: remove invalid symbloic link
  shell:
    rm -rf /usr/local/nginx/_conf/conf
  sudo: yes

- name: copy nginx base conf
  command:
    rsync -a /usr/local/nginx/_conf/ /var/nginx/conf/
  sudo: yes

- name: create symbolic link
  file:
    src=/var/nginx/{{ item.path }} path=/usr/local/nginx/{{ item.path }} state=link
  with_items:
    - {path: "conf"}
    - {path: "logs"}
  sudo: yes

- name: change ownder conf nginx
  command:
    chown -R nobody:nobody /var/nginx/conf/
  sudo: yes

- name: copy common data
  copy: src=html/common/ dest=/var/nginx/data/ owner=nobody group=users mode=0644
  sudo: yes

- name: copy html
  copy: src=html/default/ dest=/var/nginx/data/ owner=nobody group=nobody mode=0644
  sudo: yes

- name: copy nginx common conf
  copy: src=conf/common/ dest=/var/nginx/conf/ owner=nobody group=nobody mode=0644
  sudo: yes

- name: copy nginx cert conf
  copy: src=cert/ dest=/var/nginx/conf/cert owner=nobody group=nobody mode=0644
  sudo: yes

- name: copy nginx vhost conf
  template:
    src=default/{{ item.src }} dest=/var/nginx/conf/nginx-vhost-{{ app_name }}.conf owner=nobody group=nobody mode=0644
  with_items:
    - {src: nginx-vhost-template.conf.j2 }
  sudo: yes

- name: copy vhost location common
  template:
    src={{ item.src }} dest=/var/nginx/conf/{{ item.dest }} owner=nobody group=nobody mode=0644
  with_items:
    - {src: vhost-location-common-template.conf.j2, dest: vhost-location-common.conf}
  sudo: yes

- name: copy upstream
  template:
    src=default/{{ item.src }} dest=/var/nginx/conf/{{ item.dest }}-{{app_name}}.conf owner=nobody group=nobody mode=0644
  with_items:
    - {src: upstream-full-template.conf.j2, dest: upstream}
    - {src: upstream-full-template.conf.j2, dest: upstream-full}
    - {src: upstream-deploy1-template.conf.j2, dest: upstream-deploy1}
    - {src: upstream-deploy2-template.conf.j2, dest: upstream-deploy2}
  sudo: yes

- name: create deploy based directory
  file: path=/home/deploy/{{ item.path }} owner=deploy group=users state=directory recurse=yes
  with_items:
    - {path: "conf"}
    - {path: "logs"}
    - {path: "service/nginx"}
  sudo: yes

- name: create deploy based symbolic link
  file:
    src=/var/nginx/{{ item.path }} path=/home/deploy/{{ item.path }}/nginx state=link
  with_items:
    - {path: "conf"}
    - {path: "logs"}
  sudo: yes